# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=1000)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookbook', to='review.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useruser', to='review.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='multi',
            name='book',
        ),
        migrations.RemoveField(
            model_name='multi',
            name='user',
        ),
        migrations.DeleteModel(
            name='Multi',
        ),
    ]
